### ISSUE TITLE
Still have unmet dependencies.

### ISSUE THREAD

**Issue by edamame43** [parfenovds/AnkiOnRaspbian#1]
After following the steps here is the output on my pi 4 buster:
`You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 anki : Depends: python3-pyaudio but it is not going to be installed
        Depends: python3-markdown but it is not going to be installed
        Depends: libjs-jquery-flot but it is not going to be installed
 python3-pyqt5.qtserialport : Depends: python3-pyqt5 (= 5.11.3+dfsg-1+rpi1+b3) but 5.11.3+dfsg-1+b3 is to be installed
 python3-pyqt5.qtsvg : Depends: python3-pyqt5 (= 5.11.3+dfsg-1+rpi1+b3) but 5.11.3+dfsg-1+b3 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
`
then I do sudo apt --fix-broken install as suggested and try again:
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 anki : Depends: python3-pyqt5.qtwebengine (> 5.11) but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Comment by parfenovds** [comment]
I've recently tried all the steps on clear installations (rpi 3 and 3b), all works.
Could you post here full output of the 2nd step?

**Comment by edamame43** [comment]
"Some packages could not be installed....." is the output, specifically python3-pyqt5.qtwebengine package I think, but idk how to resovle it

**Comment by parfenovds** [comment]
Ok, let's try this:
1. What's the version of your os? Raspbian buster, winter edition? (~jan-feb)?
2. It's not a clear installation? Have you already tried to install anki on this system before? Could you try with a clear one?
3. Base git question: have you properly clone the repo and cd into it before actions? Have you copied full command from step 2?

**Comment by edamame43** [comment]
This is the first time installing it. and I've done all the steps. the only thing I suspect is I've changed the source file to speed up installations and upgrades but not sure how it could affect it. Could you check the version of python3-pyqt5.qtwebengine package in your system?

**Comment by parfenovds** [comment]
Mine is 5.14.0-2+b1.
Are you sure you took an appropriate source file?
You can take all the files on the https://packages.debian.org.
But, I think, It's a bit easier to take them from the repo...
For example, python3-pyqt5.qtwebengine is here:
https://packages.debian.org/sid/python3-pyqt5.qtwebengine
One more thing: don't forget to take the armhf version of all the sources.

**Comment by edamame43** [comment]
How come you have 5.14 when the package in your repo has 5.11? have you done an upgrade after the install? I can't mannuly install 5.14 because several packages from your repo files have lower versions:
`python3-pyqt5.qtwebengine depends on python3-pyqt5.qtwebchannel (>= 5.12); however:
  Version of python3-pyqt5.qtwebchannel on system is 5.11.3+dfsg-1+rpi1+b3.
 python3-pyqt5.qtwebengine depends on python3 (>= 3.8~); however:
  Version of python3 on system is 3.7.3-1.
 python3-pyqt5.qtwebengine depends on libgcc-s1 (>= 3.5); however:
  Package libgcc-s1 is not installed.
 python3-pyqt5.qtwebengine depends on libqt5webenginecore5 (>= 5.12.2); however:
  Version of libqt5webenginecore5:armhf on system is 5.11.3+dfsg-2+deb10u1.
 python3-pyqt5.qtwebengine depends on libqt5webenginewidgets5 (>= 5.12.2); however:
  Version of libqt5webenginewidgets5:armhf on system is 5.11.3+dfsg-2+deb10u1.
 python3-pyqt5.qtwebengine depends on sip-py3api-12.7; however:
  Package sip-py3api-12.7 is not installed.
`
Maybe I can't use your files on pi 4b?

**Comment by parfenovds** [comment]
I think you should try to make a clear installation with files from the repo only (they are a bit outdated, but it's ok for our purpose). They do have a connection between each other (including the versions), so I think you were right: the problem is another source, taken from somewhere but not from the repo.

**Comment by edamame43** [comment]
[https://www.raspberrypi.org/forums/viewtopic.php?t=260212](url) The exact problem I have. I've refreshed my sources and upgraded, still no luck.

**Comment by parfenovds** [comment]
Ok, I see.
I'd still suggest you to take an sd card, write new image into it, and do all the steps from the repo without any additions (like packages from another sources).
Fixing problems on dirty system after some failed installations is not a good way to solve this, I think.
