### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by lordzim** [parfenovds/AnkiOnRaspbian#2]
After the git clone and install all the debs, I still can’t install anki using sudo apt install anki

It output a error from missing “python3-pyqt5.qtwebengine” as stated from README

I’m kind lost over here, i’m not a developer or a Linux user, but I own a Raspberry Pi 4 running Raspbian Buster.

I did manage to install and run anki from https://github.com/gnprice/anki-jessie
But anki 2.0X is outdated

**Comment by parfenovds** [comment]
Try to install it on clear system.
And, I hope, you copied full string (it's long enough):
'''
sudo dpkg -i libqt5designer5_5.11.3-4_armhf.deb libqt5help5_5.11.3-4_armhf.deb libqt5test5_5.11.3+dfsg1-1+deb10u3_armhf.deb python3-sip_4.19.14+dfsg-2_armhf.deb python3-pyqt5_5.11.3+dfsg-1+b3_armhf.deb libqt5qml5_5.11.3-4_armhf.deb libqt5webchannel5_5.11.3-2_armhf.deb python3-pyqt5.qtwebchannel_5.11.3+dfsg-1+b3_armhf.deb libqt5webengine-data_5.11.3+dfsg-2+deb10u1_all.deb libqt5quick5_5.11.3-4_armhf.deb libminizip1_1.1-8+b1_armhf.deb libqt5positioning5_5.11.3+dfsg-2_armhf.deb libre2-5_20190101+dfsg-2_armhf.deb libqt5webenginecore5_5.11.3+dfsg-2+deb10u1_armhf.deb libqt5webengine5_5.11.3+dfsg-2+deb10u1_armhf.deb libqt5quickwidgets5_5.11.3-4_armhf.deb libqt5webenginewidgets5_5.11.3+dfsg-2+deb10u1_armhf.deb python3-pyqt5.qtwebengine_5.11.3+dfsg-1+b3_armhf.deb
'''
It's important to install all of them in this order.
