### ISSUE TITLE
[Question] Where all packages come from?

### ISSUE THREAD

**Issue by ekawahyu** [parfenovds/AnkiOnRaspbian#4]
I have a question. I am trying to figure out where all this .deb packages come from? I looked into raspbian repo and most of them are not available in there. Were they manually build and package from the source? Thank you.

**Comment by parfenovds** [comment]
Hello!
All packages are from [here](https://packages.debian.org/buster/).

**Comment by ekawahyu** [comment]
ah! so installing the debian package onto raspbian works out of the box? neat!
