### ISSUE TITLE
[Not an Issue] Just a token of appreciation!

### ISSUE THREAD

**Issue by kedarmhaswade** [parfenovds/AnkiOnRaspbian#5]
Thank you for taking time to document this procedure. I am happy to report that this works as expected (although some packages may get downgraded as a result) (e.g. `dpkg: warning: downgrading libqt5test5:armhf from 5.11.3+dfsg1-1+rpi1+deb10u3 to 5.11.3+dfsg1-1+d`).

Couldn't be happier to see Anki working on Raspbian!

**Comment by kedarmhaswade** [comment]
Already closed!

**Comment by parfenovds** [comment]
Glad to hear it!
Best regards!
