### ISSUE TITLE
How to start anki on Raspberry Pi?

### ISSUE THREAD

**Issue by fabriciojon** [parfenovds/AnkiOnRaspbian#6]
Hello Dmitry,
I did follow Your instructions from https://github.com/parfenovds/AnkiOnRaspbian#readme in order to install Anki on my raspberry pi 4.
Now I don't know how to launch installed Anki:
* I can't find any entry in "main menu" for anki
* I can't start anki from terminal (anki: command not found)

Could You tell me please, how should i be able to launch anki on my raspberry pi 4?
Thanks in advance

**Comment by parfenovds** [comment]
Hello!
What's your output for
`sudo apt install anki`
?

**Comment by fabriciojon** [comment]
pi@raspberrypi:~ $ sudo apt install anki
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 anki : Depends: python3-pyqt5.qtwebengine (> 5.11) but it is not installable
        Recommends: python3-matplotlib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.


During my first attempt of installation (as described in https://github.com/parfenovds/AnkiOnRaspbian#readme) i did not receive the message.

**Comment by fabriciojon** [comment]
I think that my first installation was correct. And I assume that it was "broken" after I executed 'sudo apt-get update'.
I rerun the installation (as described in https://github.com/parfenovds/AnkiOnRaspbian#readme) and now can start anki from main menu.
Does it mean i may not execute 'sudo apt-get update', because it will update packages required by Anki and make it unusable?

**Comment by parfenovds** [comment]
What's your output of
`sudo apt-get update`
?
The best way to get this information is experimental one =)

**Comment by fabriciojon** [comment]
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://packages.microsoft.com/repos/code stable InRelease
Reading package lists... Done

**Comment by parfenovds** [comment]
Can you launch anki now?

**Comment by fabriciojon** [comment]
Yes, and it is working fine. It is just great! (thus, closing this "issue")
Thanks a lot, Dmitry, for supporting me by solving my issue!
And thanks a lot that You provide such great solution, so anki-lovers can install it on rasp too! :)
Best regards

**Comment by parfenovds** [comment]
You're welcome!
