### ISSUE TITLE
Dependencie error and fix 

### ISSUE THREAD

**Issue by RandomAthleticsGuy** [parfenovds/AnkiOnRaspbian#7]
Hi,
First, thanks heaps. This is awesome!

Second, I ran in to some errors when trying to install Anki. :(
It seemed that one package depended on another, but because of the bit trailing the "+" in the file name, it thought it was a different version. Eg. One package found "python3-pyqt5.qtwebchannel_5.11.3+dfsg-1+b3_armhf.deb" but wanted "python3-pyqt5.qtwebchannel_5.11.3.deb"

To fix this, I had to remove the bit following the "+" in the file name, install the packages again. Afterwards I ran "sudo apt --fix-broken install", and then "sudo apt install anki". And success!

___ Steps for reference___
0. Download
git clone https://github.com/parfenovds/AnkiOnRaspbian.git
cd AnkiOnRaspbian

1. What I ran to rename the files 
_____Fix.py _____
import os
pth="/home/pi/AnkiOnRaspbian/"
for file in os.listdir(pth):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;os.rename(pth+file, pth+file.split("+")[0])

2. Install thingys (removed the +... bit here too)
sudo dpkg -i libqt5webenginecore5_5.11.3 libqt5webengine5_5.11.3 libqt5positioning5_5.11.3 python3-sip_4.19.14 libqt5designer5_5.11.3-4_armhf.deb libqt5help5_5.11.3-4_armhf.deb python3-pyqt5_5.11.3 libqt5quick5_5.11.3-4_armhf.deb libre2-5_20190101 libminizip1_1.1-8 libqt5quickwidgets5_5.11.3-4_armhf.deb libqt5test5_5.11.3 python3-pyqt5.qtsvg_5.11.3 python3-pyqt5.qtwebchannel_5.11.3.deb libqt5webchannel5_5.11.3-2_armhf.deb README.md libqt5qml5_5.11.3-4_armhf.deb python3-pyqt5.qtwebengine_5.11.3.deb libqt5webengine-data_5.11.3 python3-pyqt5.qtserialport_5.11.3 libqt5webenginewidgets5_5.11.3

3. Clean up some errors
sudo apt --fix-broken install

4. Install ANKI! :)
sudo apt install anki

5. Cellebration
yes
ctrl+c

*** Side note, it worked anyway but I probably should have left the '.deb' on the files....

**Comment by B0sh** [comment]
I got it to work, but the `sudo apt --fix-broken install` step removed qtwebengine for some reason. Once I ran it anki wouldn't install. I accidentally ran the dpkg install command again, and somehow it didn't return any errors.... Then anki installed fine. No idea why lol but if anyone else is trying to do this might as well try running the dpkg install a bunch of times if it doesn't work the first time

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libqt5serialport5 python3-pyqt5 python3-pyqt5.qtserialport
  python3-pyqt5.qtsvg python3-pyqt5.qtwebchannel
Suggested packages:
  python3-pyqt5-dbg
The following packages will be REMOVED:
  python3-pyqt5.qtwebengine
The following NEW packages will be installed:
  libqt5serialport5
The following packages will be upgraded:
  python3-pyqt5 python3-pyqt5.qtserialport python3-pyqt5.qtsvg
  python3-pyqt5.qtwebchannel
4 upgraded, 1 newly installed, 1 to remove and 116 not upgraded.
1 not fully installed or removed.
Need to get 2,094 kB of archives.
After this operation, 2,237 kB of additional disk space will be used.
```

**Comment by yuuwe-n** [comment]
Do you have any errors with python 3.9 dependency. It says packages depend on << 3.8. Do I have to install python3.8, Do i need to do any configing to set it to 3.8

**Comment by hundekuchen** [comment]
AnkiOnRaspbian works just fine for me (without the fix mentioned here) when using the raspbian version from 2021-03-25; I only get some warnings but anki seems to be running just fine...
https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-03-25/

**Comment by K33lin** [comment]
I'm trying to get Anki to run on my Pi Zero (No wifi). So far I've gotten it to install 100% using the AnkiOnRaspbian guide and

the version of RPIOS mentioned by hundekuchen [https://downloads.raspberrypi.org/raspi ... 021-03-25/](https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-03-25/)

However, when I double click the Anki desktop icon, it displays loading hourglass and then nothing. No errors no nothing. If it try to run it in the terminal with
pi@raspberrypi: ~ $ exec anki

it quits the terminal and nothing happens.

Why won't Anki run? How can I get it to run or at least see some sort of error message? @hundekuchen @parfenovds

**Comment by parfenovds** [comment]
Try to type ```anki``` with no ```exec``` in terminal, there should be error output.
Or maybe not - don't have anki with any problems now..
Try it anyway

**Comment by K33lin** [comment]
@parfenovds Thanks so much for responding.

I did as you said, just `anki` in terminal and it says
Illegal instruction

Thoughts? Again this is on a pi zero

**Comment by parfenovds** [comment]
@K33lin, in my opinion, you should ask [here](https://forums.ankiweb.net/), those guys knows everything about anki desktop =)
